name: smartangkot
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  google_maps_flutter: ^0.4.0
  datetime_picker_formfield: ^0.1.8
  curved_navigation_bar: ^0.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true